Mobweb.web/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Mobweb.web.Models
{
    public class Usuario
    {
        public int UsuarioID { get; set; }

        [Required(ErrorMessage = "Digite seu nome de usuario.")]
        [Display(Name = "Nome de usuario:")]
        [RegularExpression(@"^\w*", ErrorMessage = "o nome de usuario não deve conter character especiais.")]
        public string NomeUsuario { get; set; }

        [Required(ErrorMessage = "Digite sua senha.")]
        [Display(Name = "Senha:")]
        [RegularExpression(@"^\w*$", ErrorMessage ="Senha não deve conter character especiais.")]
        public string Senha { get; set; }

        [Required(ErrorMessage = "Digite seu nome completo")]
        [Display(Name="Nome Completo:")]
        [RegularExpression(@"^[A-z' ']*$",ErrorMessage ="Nome Invalido")]
        public string NomeCompleto { get; set; }

        [Display(Name = "E-mail:")]
        [RegularExpression(@"^\w*(\.\w*)?@\w*\.[a-z]+(\.[a-z]+)?$",ErrorMessage ="Email Invalido")]
        public string Email { get; set; }

        [Display(Name = "Telefone:")]
        public string Telefone { get; set; }

        public virtual ICollection<Cliente> Clientes { get; set; }

    }
}

Mobweb.web/Controllers/ClienteController.cs
using Mobweb.web.Helpers;
using Mobweb.web.Models;
using Mobweb.web.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Mobweb.web.Controllers
{
    public class ClienteController : Controller
    {
        ClienteService clienteService = new ClienteService();
        UsuarioService userService = new UsuarioService();


        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create([Bind(Include = "ClienteID,RazaoSocial,NomeFantasia,CNPJ,Logradouro,Numero,Bairro,Complemento,Municio,Cep,UsuarioID")] Cliente client)
        {
            if (clienteService.ValidarCNPJ(client.CNPJ))
            {
                int usuarioID = userService.GetUsuarioByLogin(User.Identity.Name).UsuarioID;
                client.UsuarioID = usuarioID;
                clienteService.CreateClient(client);
                return RedirectToAction("Clients", "Usuario");
            }
            else
            {
                ModelState.AddModelError("", "CNPJ invalido.");
                return View();
            }
           
        }

        [Authorize]
        public ActionResult Details(int? id)
        {
            if(id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario user = userService.GetUsuarioByLogin(User.Identity.Name);
            Cliente client = clienteService.GetClientByID((int)id);
            if(client.UsuarioID!=user.UsuarioID)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            return View(client);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Details([Bind(Include = "ClienteID,RazaoSocial,NomeFantasia,CNPJ,Logradouro,Numero,Bairro,Complemento,Municio,Cep,UsuarioID")] Cliente cliente)
        {
            clienteService.Update(cliente);
            return View(cliente);
        }

        [Authorize]
        public ActionResult Remove(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Usuario user = userService.GetUsuarioByLogin(User.Identity.Name);
            Cliente client = clienteService.GetClientByID((int)id);
            if (client.UsuarioID != user.UsuarioID)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            clienteService.Remove(client.ClienteID);
            return RedirectToAction("Clients", "Usuario");
        }

        [Authorize]
        public string CheckCNPJ(string cnpj)
        {
            if (MasterValidator.ValidarCNPJ(cnpj))
            {
                if (clienteService.ExistCNPJ(cnpj))
                    return "CNPJ já cadastrado no sistema.";
                else
                    return "CNPJ valido.";
            }
            return "CNPJ invalido.";
        }

        [Authorize]
        public string CheckCNPJWithID(string cnpj,int clienteID)
        {
            if (MasterValidator.ValidarCNPJ(cnpj))
            {
                if (clienteService.ExistCNPJWithID(cnpj,clienteID))
                    return "CNPJ já cadastrado no sistema.";
                else
                    return "CNPJ valido.";
            }
            return "CNPJ invalido.";
        }

    }
}

Mobweb.web/Controllers/UsuarioController.cs
using Mobweb.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Mobweb.web.Helpers;
using Mobweb.web.Services;
using System.Net;
using Mobweb.web.DAL;
using System.Data.Entity;

namespace Mobweb.web.Controllers
{
    public class UsuarioController : Controller
    {

        private UsuarioService userService = new UsuarioService();
       [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            if (Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(ContaViewModel usuario,string returnUrl)
        {
            if (Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            if (!ModelState.IsValid)
            {
                return View(usuario);
            }
            
            var achou = userService.GetLogin(usuario);
            //achou = true;
            
            if (achou!=null)
            {
                FormsAuthentication.SetAuthCookie(usuario.UserName, usuario.LembrarMe);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Login e/ou senha Invalidos!");
            }
            return View();
        }

        [AllowAnonymous]
        public ActionResult SignIn()
        {
            if (Request.IsAuthenticated)
            {
               return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [Authorize]
        public ActionResult Details()
        {
            Usuario user = userService.GetUsuarioByLogin(User.Identity.Name);
         
                if(user==null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            else
            {
                return View(user);
            }
                
        }

        [HttpPost]
        [Authorize]
        public ActionResult Details([Bind(Include = "UsuarioID,NomeUsuario,Senha,NomeCompleto,Email,Telefone")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
               Usuario userTemp = userService.GetUsuarioByID(usuario.UsuarioID);

               userService.Update(usuario);
               FormsAuthentication.SignOut();
               FormsAuthentication.SetAuthCookie(usuario.NomeUsuario, false);

            }
            return View(usuario);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult SignIn([Bind(Include = "UsuarioID,NomeUsuario,Senha,NomeCompleto,Email,Telefone")] Usuario usuario)
        {
            switch (userService.CreateUsuario(usuario))
            {
                case 2:
                    ModelState.AddModelError("", "Usuario ja existe no sistema");
                    break;
                case 3:
                    ModelState.AddModelError("", "Email ja cadastrado.");
                    break;
                case 1:
                    return RedirectToAction("Login");
                    
            }
            return View();
        }

        public ActionResult Clients()
        {
            Usuario user = userService.GetUsuarioByLogin(User.Identity.Name);
            if (user != null)
            {
                List<Cliente> lista = userService.GetClientesByUserID(user.UsuarioID);
                if (lista == null)
                    lista = new List<Cliente>();
                return View(lista);
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [AllowAnonymous]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Mobweb.web/Views/Usuario/Clients.cshtml
@model IEnumerable<Mobweb.web.Models.Cliente>
@{
            

                ViewBag.Title = "Clients";
}
<div class="col-xs-12">
    <div class="box">
        <div class="box-header">
            <h3 class="box-title">Clientes</h3>
        </div>
        <div class="label">
            <a id="newClientBTN" href="@Url.Action("Create","Cliente")" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i>&nbsp; Adicionar</a>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
            <table id="clientes" class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Razão Social</th>
                        <th>CNPJ</th>
                        <th>Localização</th>
                        <th>ações</th>
                    </tr>
                </thead>
                <tbody> 
                        @foreach (var item in Model)
                        {
                        
                            <tr>
                                <td>@item.RazaoSocial</td>
                                <td>@item.CNPJ</td>
                                <td>@item.Municio - @item.Logradouro</td>
                                <td>
                                    <a id="editarClient" class="btn btn-primary" href="@Url.Action("Details","Cliente",new { id = item.ClienteID})"><i class="glyphicon glyphicon-pencil"></i>&nbsp; Editar</a>
                                    <a id="removerClient" class="btn btn-danger" href="@Url.Action("Remove","Cliente",new { id = item.ClienteID})" ><i class="glyphicon glyphicon-trash"></i>&nbsp; Remover</a>
                                </td>
                            </tr>
                        }
                    
                </tbody>
                <tfoot>
                    <tr>
                        <th>Razão Social</th>
                        <th>CNPJ</th>
                        <th>Localização</th>
                        <th>ações</th>
                    </tr>
                </tfoot>
            </table>
        </div>
        <!-- /.box-body -->
    </div>
    <!-- /.box -->
</div>



@section Scripts{
    <script>
        $(function () {

            $('#clientes').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': true,
                'autoWidth': false
            })
        });

        
    </script>

}

Mobweb.web/Views/Usuario/Details.cshtml
@model Mobweb.web.Models.Usuario
@{
    ViewBag.Title = "Details";

}

<div class="col-md-5 col-md-offset-3">
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Detalhes</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <div class="box-body">

            <div class="form-group">
                @Html.LabelFor(m => m.NomeUsuario)
                @Html.DisplayFor(m => m.NomeUsuario, new { @class = "form-control", @placeholder = "Digite seu nome de usuario" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NomeCompleto)
                @Html.DisplayFor(m => m.NomeCompleto, new { @class = "form-control", @placeholder = "Digite seu nome completo" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Email)
                @Html.DisplayFor(m => m.Email, new { @class = "form-control", @placeholder = "Digite seu Email" })
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Telefone)
                @Html.DisplayFor(m => m.Telefone, new { @class = "form-control", @placeholder = "(DD) 0000-0000", @id = "Phone" })

            </div>

        </div>
        <!-- /.box-body -->

        <div class="box-footer">
            @Html.ActionLink("Voltar", "Index", "Home", new { id = Model.UsuarioID }, new { @class = "btn btn-default" })
            <a id="editModal" class="btn btn-primary pull-right" role="button"><i class="glyphicon glyphicon-pencil"></i> Editar</a>
        </div>

    </div>
</div>
<div class="invisivel" id="modal_editar" role="dialog">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal" style="padding-left:15px;">
            <fieldset>
                <div class="row ">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.UsuarioID)
                    @Html.HiddenFor(model => model.NomeCompleto)
                    <div class="form-group">
                        @Html.LabelFor(m => m.NomeUsuario, new { @class = "col-md-3 control-label" })
                        <div class="col-md-12">
                            @Html.TextBoxFor(m => m.NomeUsuario, new { @class = "form-control", @id = "txt_nome" })
                            @Html.ValidationMessageFor(m => m.NomeUsuario, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Senha, new { @class = "col-md-3 control-label" })
                        <div class="col-md-12">
                            @Html.PasswordFor(m => m.Senha, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Senha, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email, new { @class = "col-md-3 control-label" })
                        <div class="col-md-12">
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Telefone, new { @class = "col-md-3 control-label" })
                        <div class="col-md-12">
                            @Html.TextBoxFor(m => m.Telefone, new { @class = "form-control", @id = "Phone" })
                            @Html.ValidationMessageFor(m => m.Telefone, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="modal-footer">
                                <a id="btn_sair" class="btn btn-default" role="button" data-dismiss="modal">cancelar</a>
                                <input type="submit" value="Salvar" class="btn btn-primary" />
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    }
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>

        $(document).on('click', '#editModal', function () {
            var modal_editar = $('#modal_editar');
            bootbox.dialog({
                title: 'Alterar Dados',
                message: modal_editar
            })
                .on('shown.bs.modal', function () {
                    modal_editar.show(0, function () {
                        $('txt_nome').focus();
                    });
                })
                .on('hidden.bs.modal', function () {
                    modal_editar.appendTo('body');
                    modal_editar.hide();
                });
        });
        $(document).ready(function () {
            $("#Phone").mask("(99)9999-9999");
        });

    </script>

}

Mobweb.web/Views/Usuario/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

Mobweb.web/Views/Usuario/Login.cshtml
@model Mobweb.web.Models.ContaViewModel

@{
    ViewBag.Title = "Login";
}


<div class="col-md-5 col-md-offset-3">

    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Login</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Usuario", null, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="box-body">
                        <div class="form-group">
                            @Html.LabelFor(m => m.UserName, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control",@placeholder="Usuario" })
                                @Html.ValidationMessageFor(m => m.UserName, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.Senha, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-10">
                                @Html.PasswordFor(m => m.Senha, new { @class = "form-control", @placeholder = "Senha" })
                                @Html.ValidationMessageFor(m => m.Senha, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <div class="checkbox">
                                    <label>
                                        @Html.CheckBoxFor(m => m.LembrarMe)
                                        @Html.LabelFor(m => m.LembrarMe)
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <label>
                                    @Html.ActionLink("Cadastre-se", "SignIn")
                                </label>
                            </div>
                        </div>

                    </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <input type="submit" class="btn btn-info pull-right" value="Sign In" />
                </div>
            }
        </section>
    </div>
</div>
    

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Mobweb.web/Views/Usuario/SignIn.cshtml
@model Mobweb.web.Models.Usuario
@{
    ViewBag.Title = "SignIn";
}
<div class="col-md-5 col-md-offset-3">


    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Inscreva-se</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="box-body">

                <div class="form-group">
                    @Html.LabelFor(m => m.NomeUsuario)
                    @Html.TextBoxFor(m => m.NomeUsuario, new { @class = "form-control", @placeholder = "Digite seu nome de usuario" })
                    @Html.ValidationMessageFor(m => m.NomeUsuario, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Senha)
                    @Html.PasswordFor(m => m.Senha, new { @class = "form-control", @placeholder = "Digite sua senha" })
                    @Html.ValidationMessageFor(m => m.Senha, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.NomeCompleto)
                    @Html.TextBoxFor(m => m.NomeCompleto, new { @class = "form-control", @placeholder = "Digite seu nome completo" })
                    @Html.ValidationMessageFor(m => m.NomeCompleto, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Email)
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Digite seu Email" })
                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.Telefone)
                    @Html.TextBoxFor(m => m.Telefone, new { @class = "form-control", @placeholder = "(DD) 0000-0000", @id = "Phone" })
                    @Html.ValidationMessageFor(m => m.Telefone, "", new { @class = "text-danger" })
                    
                </div>

            </div>
            <!-- /.box-body -->

            <div class="box-footer">
                <button type="submit" class="btn btn-primary pull-right">Inscrever</button>
                <a class="btn btn-default" href="@Url.Action("index","home")">Voltar</a>
            </div>
        }

    </div>
</div>


@section Scripts {

    <script>
        $(document).ready(function () {
            $("#Phone").mask("(99)9999-9999");
        });
    </script>

    @Scripts.Render("~/bundles/jqueryval")

}