Mobweb.web/Controllers/UsuarioController.cs
using Mobweb.web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Mobweb.web.Helpers;
using Mobweb.web.Services;
using System.Net;
using Mobweb.web.DAL;
using System.Data.Entity;

namespace Mobweb.web.Controllers
{
    public class UsuarioController : Controller
    {

        private UsuarioService userService = new UsuarioService();
       [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            if (Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(ContaViewModel usuario,string returnUrl)
        {
            if (Request.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            if (!ModelState.IsValid)
            {
                return View(usuario);
            }
            
            var achou = userService.GetLogin(usuario);
            //achou = true;
            
            if (achou!=null)
            {
                FormsAuthentication.SetAuthCookie(usuario.UserName, usuario.LembrarMe);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Login e/ou senha Invalidos!");
            }
            return View();
        }

        [AllowAnonymous]
        public ActionResult SignIn()
        {
            if (Request.IsAuthenticated)
            {
               return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [Authorize]
        public ActionResult Details()
        {
            Usuario user = userService.GetUsuarioByLogin(User.Identity.Name);
         
                if(user==null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            else
            {
                return View(user);
            }
                
        }

        [HttpPost]
        [Authorize]
        public ActionResult Details([Bind(Include = "UsuarioID,NomeUsuario,Senha,NomeCompleto,Email,Telefone")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
               Usuario userTemp = userService.GetUsuarioByID(usuario.UsuarioID);

               userService.Update(usuario);
               FormsAuthentication.SignOut();
               FormsAuthentication.SetAuthCookie(usuario.NomeUsuario, false);

            }
            return View(usuario);
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult SignIn([Bind(Include = "UsuarioID,NomeUsuario,Senha,NomeCompleto,Email,Telefone")] Usuario usuario)
        {
            switch (userService.CreateUsuario(usuario))
            {
                case 2:
                    ModelState.AddModelError("", "Usuario ja existe no sistema");
                    break;
                case 3:
                    ModelState.AddModelError("", "Email ja cadastrado.");
                    break;
                case 1:
                    return RedirectToAction("Login");
                    
            }
            return View();
        }

        public ActionResult Clients()
        {
            Usuario user = userService.GetUsuarioByLogin(User.Identity.Name);
            if (user != null)
            {
                List<Cliente> lista = userService.GetClientesByUserID(user.UsuarioID);
                if (lista == null)
                    lista = new List<Cliente>();
                return View(lista);
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        [AllowAnonymous]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Mobweb.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="hold-transition skin-blue sidebar-mini my-body" style="padding:0;">
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            @using (Html.BeginForm("Index", "Home", FormMethod.Post, new { id = "BeginLogo" }))
            {
                <a href="javascript:document.getElementById('BeginLogo').submit()" class="logo">
                    
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><b>M</b>WB</span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><b>Mob</b>WEB</span>
                </a>
            }
                <!-- Header Navbar: style can be found in header.less -->
                <nav class="navbar navbar-static-top">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                        <span class="sr-only">Toggle navigation</span>
                    </a>

                    <div class="navbar-custom-menu">
                        @if (Request.IsAuthenticated)
                        {

                            <ul class="nav navbar-nav">
                                <li><a href="#">Olá @User.Identity.Name</a></li>

                                <!-- Control Sidebar Toggle Button -->
                                <li class="dropdown">
                                    <a href="#" data-toggle="dropdown"><i class="fa fa-gears"></i></a>
                                    <ul class="dropdown-menu">
                                        <li class="dropdown-item">@Html.ActionLink("Alterar Dados", "Details", "Usuario")</li>
                                        <li class="dropdown-item">@Html.ActionLink("Sair", "LogOff", "Usuario")</li>
                                    </ul>
                                </li>
                            </ul>

                        }
                    </div>
                </nav>
            </header>
        <!-- Left side column. contains the logo and sidebar -->
        @if (Request.IsAuthenticated)
        {
            <aside class="main-sidebar">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- /.search form -->
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu" data-widget="tree">
                        <li class="header">Serviços</li>
                        @if (Request.IsAuthenticated)
                        {
                            <li class="treeview">
                                <a href="#">
                                    <i class="fa fa-users"></i> <span>Clients</span>
                                    <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                                </a>
                                <ul class="treeview-menu">
                                    <li><a href="@Url.Action("Clients","Usuario")"><i class="fa fa-address-book-o"></i> Client List</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                </section>
                <!-- /.sidebar -->
            </aside>
        }
            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <div class="content" >
                    <div class="row">
                        @RenderBody()
                    </div>
                   
                </div>


                <!-- Main content -->
                <!-- /.content -->
            </div>
            <!-- /.content-wrapper -->
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Version</b> 2.4.0
                </div>
                <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
                reserved.
            </footer>

            <!-- Control Sidebar -->
            <!-- /.control-sidebar -->
            <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
            <div class="control-sidebar-bg"></div>
        </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
</body>
</html>